### ISSUE TITLE
Questionnaire for partners

### ISSUE THREAD

**Issue by bvhme** [score-partners/score.partners#24]
We want to send everyone an email with 1 simple multiple choice question:

Options:

* Is anything in SCORE impeding your progress?
* Where are you in SCORE?

**Comment by clausmullie** [comment]
Answers:
* Internal & setting up (no collaboration)
* Internal & looking for connections to start conversations about working groups 
* Ready to start working groups

**Comment by clausmullie** [comment]
* Happy to continue working internally
* Working internally, but ready for guidance on how to start collaborating with others
* Ready for full collaboration with other partners

**Comment by bvhme** [comment]
I think they should be more practical situations they can recognise themselves in probably, perhaps something like:

* I'm trying to find out in my organisation who could work on SCORE
* I'm working with people inside of our organisation to find out how to get SCORE to work
* I'm collaborating with other organisations to find out how to work on SCORE

**Comment by clausmullie** [comment]
I like top & we could add:

open question - what is your ambition within score in the next 3 months? 
multiple choice question - what PM tasks would you like to see prioritised over next 3 months?

**Comment by clausmullie** [comment]
question to add:

information - overloaded/under-informed/just right
