### ISSUE TITLE
Involve the owners of the GitHub organisations of the partner cities involved

### ISSUE THREAD

**Issue by bvhme** [score-partners/score.partners#28]

**Comment by clausmullie** [comment]
We created this issue to try generate more traction from the technical teams in these organizations. 

However, all partners are now working in a self-motivated fashion, addressing the priorities they have in their daily work. 

Those that are in active development have technical staff who are already involved. 

I feel bringing in more staff members might distract from the partner's current priorities or advancing their working groups and deliverables. 

We could consider reopening this issue once the first round of working groups have reached a sense of completion or significant milestone.
