### ISSUE TITLE
Status dashboard for every deliverable and working group in SCORE.

### ISSUE THREAD

**Issue by bvhme** [score-partners/score.partners#33]
To go on the Dashboard:

## Working Group (Working Group Leads)

Per working group:

* Which step in the process is the Working Group at
* What is stopping progress

## Partner (All partners)

Yes/No questions

* We have easy access to the information we need
* We have meaningful communication with other partners
* We know what to do
* We are making progress
* We are creating value

## Deliverables (Work Package Leaders)

Per deliverable status which is one of:

* Upcoming
* In progress
* Over due
* Done

**Comment by clausmullie** [comment]
We can use this to collate google form entries 
http://www.alicekeeler.com/2015/01/08/multiple-google-forms-to-one-spreadsheet/

**Comment by clausmullie** [comment]
**Model:**
Single questionnaire with conditional logic
We pre fill one for each partner with blank data
We send them their edit links 
Each month we resend them edit links to same entry
We have a script to autoupdate score.partners (incl last edit) 



Operationally

**Comment by bvhme** [comment]
I've uploaded the Dashboard page to http://score.partners/status/

For us to Beta test there
