### ISSUE TITLE
Solution Definition template

### ISSUE THREAD

**Issue by bvhme** [score-partners/score.partners#43]

**Comment by bvhme** [comment]
I think the goal here is to transition out of the ['research phase'](http://score.partners/process/2-research.html) and in to the ['definition phase'](http://score.partners/process/3-definition.html) of the SCORE process.

The question here is has the following roughly been achieved?

- [ ] Common architecture
- [ ] Research
- [ ] Commit

Shall we just make a Google Doc with the main headings from the 'definition phase' and have them be filled in?

This document should serve as a living document that replaces the 'specifications' in the development process.

**Comment by bvhme** [comment]
Joran is working on this

**Comment by clausmullie** [comment]
The work package leader for WP4 Solution development is currently doing this through factsheets in the google drive and shared on the community. 

I will close this for now. We will probably do this as part of the '[productification](https://about.publiccode.net/activities/codebase-stewardship/activities.html)' phase for SCORE generated codebases which are mature enough.
