### ISSUE TITLE
Change name

### ISSUE THREAD

**Issue by clausmullie** [score-partners/score.partners#78]
I would change this 'from partners' to 'for participants'  - as it's also for non SCORE partners

**Comment by bvhme** [comment]
I don't think participants is the right word. I think partners can also hold up in a collaboration, as in a _collaboration partner_ which in my opinion makes more sense than a _collaboration participant_, however, perhaps I'm looking in the wrong direction here.

**Comment by clausmullie** [comment]
agreed
