### ISSUE TITLE
Do we want a code of conduct for score community?

### ISSUE THREAD

**Issue by clausmullie** [score-partners/score.partners#9]

**Comment by bvhme** [comment]
This is a worthwhile question. I've removed the one that Discourse came with standard, however it is always wise to have some kind of Code of Conduct. Perhpaps we can adopt the 'contributor covenant' for all of SCORE.

My instinct was that all these people now should be able to deal, but I now realise that it is a lot easier to start a project with a Code of Conduct than impose one later on.
